Main menu v2 (#48)
* v1 not working

* create main and move gui into steam mod creator file

* manually add logging and debug stuff to main

* move imports up

* use main logger in steam mod creator

* Reanme main menu to ck 3 mod template

* remove exception handling it is now in main

* comment out not needed code

* settings implemented

* make light dark mode switch work

* hide main window initially so fist start only has 1 window

* Dark mode cause light attracts bugs ;)

* make settings directly apply without needing to restart

* fix crashing and also apply style to mod maker

* fix error by not outputting it and destroying settings window

* Show current version in main menu with colors

* add version to welcome page (only in inital setup)

* update settings light dark mod to work correctly
Fixed an issue with an error being thrown:
Error saving settings: bad window path name ".!toplevel.!frame.!combobox"
_tkinter.TclError: bad window path name ".!toplevel.!frame.!combobox"

* use configure application style to change theme on settings save

* dont show error message for combobox because it works even with the error showing

* remove apply theme def because no longer needed

* make use of log level set in settings i ´n backend

* use new logging levels:
Changed global exception handler to use logger.critical() instead of logger.error()

* remove commented out code for window resize event to save window size

* move configure_application_style into styles ui file

* make settings show light and dark instead of flatly and dark

* fix it so backend still uses flatly but frontend displays light and dark